Externals.cfg
Bringing hotfix back to master.
=> Update from hotfix in other repo.

AdvCore_GridCompMod.F90
Must register grids in advcore if running in stadalone mode like ctm
=> Register grids in advcore

Externals.cfg, FV_StateMod.F90
This gets the FMS name change into the master externals
=> Merge develop into master

DynCore_GridCompMod.F90, FV_StateMod.F90
This is a hand merge to resolve conflicts in pull request "cvs to git updates2 #27".
=> Cvs to git updates handmerge

FV_StateMod.F90
Git got a bit confused since both branches had the code. Hopefully it's happy now.
=> Result of Handmerge of develop into MAPL 2.0

interp_restarts.F90
=> Fix interp_restarts.x crash caused by MAPL 2.1

CMakeLists.txt, Externals.cfg
This commit will allow JEDI to build with GEOS.
Tested with AMIP and Coupled.
=> Additional fixes for JEDI integration

scripts/fv3.j
Fixing some elements of fv3.j to make it "more correct"
=> Various fixes for fv3.j

scripts/fv3.j
=> Merge develop into main

.circleci/config.yml
Adds CI for FV3 GC including an FV3 Standalone run
=> Add CircleCI build for FVdycoreCubed_GridComp

.circleci/config.yml, Externals.cfg
Now let's pull `develop` into `main` (which is just the CircleCI fix)
=> Pull Develop into main

scripts/fv3.j
This is needed as MAPL might soon be a shared library
=> Add GEOSDIR/lib to LD_LIBRARY_PATH

.circleci/config.yml, scripts/fv3.j
This pulls `develop` into `main`
=> Merge develop into main for release [ci skip]

FV_StateMod.F90
This is to get the fix from @aoloso. Doing it by hand because GitHub is weird.
=> Handmerge main into develop

.circleci/config.yml, interp_restarts.F90
Fixes #99 
Bug in handling agcm_import_rst
=> Fixes issue #99

CMakeLists.txt
GFE libraries use CMake namespace.
=> Use GFE Namespace

StandAlone_AdvCore.F90, StandAlone_DynAdvCore.F90, StandAlone_FV3_Dycore.F90
This PR should be approved after MAPL's PR https://github.com/GEOS-ESM/MAPL/pull/846
=> follow MAPL's change to add a new MAPL_CapOptions constructor

.circleci/config.yml
This fixes up the CI to make it readable
=> Fix up CI names

.circleci/config.yml, StandAlone_AdvCore.F90, StandAlone_DynAdvCore.F90, StandAlone_FV3_Dycore.F90
Implements changes/simplifications of MAPL FLAP introduced in MAPL V3.
=> MAPL V3 FLAP usage simplification

fv_regrid_c2c.F90, fv_regrid_c2c_bin.F90, fv_regridding_utils.F90
what the title says, needed for CTM
=> Update so that interp_restarts.x will build when FV_PRECISION=R8

.circleci/config.yml
This updates the CI here to use Baselibs 7.5.0
=> Update CI to Baselibs 7.5.0

.circleci/config.yml, DynCore_GridCompMod.F90, FV_StateMod.F90
This supersedes #167 as it fixes up the conflict with CI.
=> Handmerge develop into MAPL3 - 2022-Jul-13

.circleci/config.yml
This brings in the FV3 update.
=> Merge Develop into Main for Release

DynCore_GridCompMod.F90
Modified ADD_INCS to properly export Wind Tendencies incorporating AtoD and DtoA transforms.
=> Modified ADD_INCS to properly export Wind Tendencies

.circleci/config.yml, CMakeLists.txt, CubeToLatLon.F90, DynCore_GridCompMod.F90, FV_StateMod.F90, fv_regrid_c2c.F90
Changes were mad to restore ability to build and run with double precision.
=> Changes to get FVdycoreCubed_GridComp compiled with double -r8

DynCore_GridCompMod.F90, FV_StateMod.F90
Take with [fvdycore #63](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/63)
=> Additional updates for GCM v11.0.0-rc.1

interp_restarts.F90
This fixes a bug when trying to regrid the agcm_import_rst file in interp_restart.x
This adds the stretching parameters to the output files if passed to interp_restart.x
=> Bug fixes in interp_restart.x

.circleci/config.yml, README.md
This PR fixes the CI in the MAPL 3 branch.
=> Fix for CI in MAPL3 Branch

scripts/fv3.j, scripts/fv3_setup
Added singularity checks to fv3_setup and fv3.j
=> Singularity checks

scripts/fv3.j, scripts/fv3_setup
Updates from @AnikMumssen21 for singularity work.
=> Updated to clean up scripts for NOT singularity

scripts/fv3_setup
This PR has updates needed for running on the Milan processors on SCU17 at NCCS.
Note that currently to run on SCU17, you must build on SCU17 due to OS differences.
=> Updates for SCU17

scripts/fv3.j, scripts/fv3_setup
This requires [GFDL_atmos_cubed_sphere geos/v2.7.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv2.7.0) but is zero diff
=> GitFlow: Merge develop into main for release

FV_StateMod.F90
Changes introduced by @wmputman
=> NWP Patches

.circleci/config.yml, FV_StateMod.F90, scripts/fv3_setup
Notable changes for DSL port:
- `adiabatic_init`: one-time cost, won't port
- adjustments to damping options: no-op
=> Update to `2.11.0`

.circleci/config.yml
This PR adds a GCM run to this repo. I thought it had it and I want to say it did at some point but now it's gone. Huh.
=> Add GCM run to CI

CMakeLists.txt, fv_regrid_c2c.F90, fv_regrid_c2c_bin.F90, interp_restarts.F90, interp_restarts_bin.F90, rs_scaleMod.F90
Updating to be consisten with MAPL3
=> updating gftl

.github/workflows/validate_yaml_files.yml
This is a handmerge on CLI of `develop` into `feature/sdrabenh/gcm_v12`
=> Handmerge of develop into v12

scripts/fv3_setup
Removes the SLES12/SLES15 distinction at NCCS
=> v12: Remove NCCS OS detection

scripts/fv3.j, scripts/fv3_setup
This is an attempt to clean up the `fv3_setup` and `fv3.j` scripts. They were a bit ugly.
=> v11: Clean up fv3_setup and fv3.j
