GEOS-ESM/FVdycoreCubed_GridComp

FV_StateMod.F90

This fixes #7 and is separate from my other PR which is for the dev/MAPL-2.0 branch while this is a hotfix for master.
Without this the CTM crashes, and this initialization is already present in the r4 version.

Initialize uc and vc to 0d0 in computeMassFluxesR8

---

DynCore_GridCompMod.F90
StandAlone_DynAdvCore_GridCompMod.F90

Fixes #21 
This fixes issue 21 that the standalone dynadv core driver was broken. The driver's main grid comp was trying to add the fields in the tradv bundle from dyncore into the tradv bundle in the advcore. Apparently this is no longer necessary as somehow thru the magic of mapl the fact that dyncore has populated the tradv bundle means that advcore's tradv bundle has also been filled, must be sharing pointers underneath. 
In addition to look at the advected tracers it was necessary to add code.  The tradv bundle is not exported. In standalone mode an export bundle tradvex is created and the fields in tradv are copied to this bundle. Just copying the fields in the tradv bundle to tradvex that history can use is not enough. They need extra decoration that the mapl field creation …

Fix standalone dynadv driver

---

FV_StateMod.F90

This makes it possible to build  FV in double precision.  It is a zero-diff change for single precision.

Resolved type issue for UH25 export

---

Externals.cfg

This moves `Externals.cfg` to version v1.1.2 of GFDL_atmos_cubed_sphere (aka fvdycore). 
Needed for release to GCM.

Update to fvdycore geos/v1.1.2

---

scripts/fv3.j

As found by @karthik-vm of OSU, the default value of `domains_stack_size` in `fv3.j` is a rather impressive 240,000,000:
https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/6b8ea53d00102a124d590a70d8f0103736f1d1b1/scripts/fv3.j#L258-L261
Compared to the value in the default `fvcore_layout.rc` in GEOSgcm_App it is 10x larger:
```
&fms_nml
print_memory_usage=.false.
domains_stack_size = 24000000
/
```
As we cannot guarantee systems outside of NASA are configured such that it would allow 240,000,000, reduce stacksize to be consistent with the default for the GEOS GCM.

Lower FV3 standalone stacksize

---

scripts/fv3_setup

On some CI systems, rsync might not be available. For this simple task, use cp.

Use cp instead of rsync

---

scripts/fv3.j
scripts/fv3_setup

This PR resolves https://github.com/GEOS-ESM/GEOSfvdycore/issues/26.
This essentially allows one to actually use the IOSERVER in FV3 Standalone. The older code was incomplete at best and useless in actuality.

Make IOSERVER usable with FV3 Standalone

---

Externals.cfg

This is in relation to the move to `mepo`. Just removes `Externals.cfg`

Remove manage_externals support

---

AdvCore_GridCompMod.F90

- Modified the code so that up to the first ntracers advected tracers are passed to AdvCore EXPORT state. 
- The changes do not affect at all any CTM experiment. 
- The section of the code where the changes were made, is only use for diagnostics.

Modified conditional statements  to access AdvCore EXPORT pointers only when needed

---

CMakeLists.txt
fv_regrid_c2c.F90
fv_regrid_c2c_bin.F90
fv_regridding_utils.F90
interp_restarts.F90
interp_restarts_bin.F90
rs_scaleMod.F90

This is a refactoring of interp_restarts.x to support new restart types. GOCART2G will be producing restarts that have a "level" and an "ungridded dimension". In addition hemco now has a 2D-only restart. These are not currently supported. So I have done the following:
* Moved all routines needed for interp_restarts.x. to in this repo to make it easier to maintain
* Split interp_restarts.x into to programs, one for binary that really should not have to change ever as we are no longer using this in current and new systems, and another for NetCDF that I can focus on improving, cleaning, and adding new features as needed.
* Extended the NetCDF version so support the new kinds of restarts that will be coming with GOCART2G.
I have tested this for zero-diff, both both the binary and NetCDF …

Refactor and update interp_restarts.x for new restart types

---

fv_regrid_c2c.F90

My previous commit had a bug. I introduced a read_topo routine but didn't realize I need to pass in arrays with explicit bounds as the arrays in the calling procedure are haloed.

Fix bug when calling read_topo

---

scripts/CMakeLists.txt
scripts/fv3_setup

Now that NAS defaults to TOSS nodes, we can fix up the `gcm_setup`, et al, scripts to be more generic.

WORK IN PROGRESS: Update NAS nodes for TOSS

---

AdvCore_GridCompMod.F90

When the user does NOT want to exclude advection tracers, there is currently no way to safely ensure this without causing a warning to be pushed to stdout on every time step. This can now be prevented by setting `EXCLUDE_ADVECTION_TRACERS: NO` in the relevant resource file.

Squash unnecessary warning from FVdycore

---

CMakeLists.txt

Due to insufficient grepping on my part, some remnants of the
"non-canonical" CMake still remain. Apparently these were not necessary
changes for Spack, but they are changes that unify the CMake style of
GEOS to be more like "correct" CMake.
In this go-around, it is mainly finding `INC_ESMF` which I apparently
forgot to grep for last time (I was focused on NetCDF), and some
non-canonical OpenMP calls.
See https://github.com/GEOS-ESM/GEOSgcm/issues/387 for the meta-issue.

Updates for Spack Support, Round 2

---

.circleci/config.yml
DynCore_GridCompMod.F90
FV_StateMod.F90

Closes #165 
This PR initializes `FV_Atm(1)%ks` by doing:
```fortran
FV_Atm(1)%ks = count(bk == 0.0) - 1
```
per @atrayano 
ETA: Note I also updated the CI because it was old and broken.
Note: use "hide whitespace" to see easier. My editor removes unneeded trailing spaces and went a bit crazy here:

Fixes #165. Initialze ks with bk

---

.circleci/config.yml
scripts/fv3_setup

Runs of `fv3.j` on AWS by @nosolls recently found that AWS is not quite handled correctly. The main issue is that ioserver hasn't really been tested well (or at all) on AWS. So, like we do in [gcm_setup](https://github.com/GEOS-ESM/GEOSgcm_App/blob/develop/gcm_setup), we turn off ioserver.
Also, just some generic cleanup.
Note: This needs testing. Both on AWS as well as NCCS and desktops. Make sure I didn't break anything.

Add AWS to fv3_setup

---

scripts/CMakeLists.txt
scripts/fv3.j
scripts/fv3_setup

This PR is an attempt to add support for Singularity testing. It actually does something more fundamental, though. Now, by default, `fv3_setup` does not copy over `StandAlone_FV3_Dycore.x` into the experiment and `fv3.j` by default will run the executable in the `install/bin` directory that was built.
It was found in Singularity testing that this was needed for Singularity runs and, in truth, is the right way to do things with CMake and RPATHs.
But, code is currently in the script that *IF* there is a `StandAlone_FV3_Dycore.x` executable in the experiment directory, it will use that one instead of the one in `install/bin`

Add experimental support for Singularity

---

CMakeLists.txt

This PR is needed for building GEOSgcm with spack-stack (see https://github.com/NOAA-EMC/spack/pull/174).
In it, we change an `INCLUDE_DIRECTORIES` to `INTERFACE_INCLUDE_DIRECTORIES`. This is needed as FMS-from-Spack uses a CMake config that does not provide `INCLUDE_DIRECTORIES`. 
Testing with GEOS using internal FMS and Baselibs show this still does work and is zero-diff.

Updates for Spack Stack

---

DynCore_GridCompMod.F90

This PR brings in the units fix in v1.2.15.1 (see https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/compare/v1.2.15...v1.2.15.1) into the `main` branch.

Fix incorrect mass flux units

---

DynCore_GridCompMod.F90
FV_StateMod.F90
scripts/fv3_setup

Proposed changes to let the FV3 Standalone work again. The issue seems to be the standalone cannot call some replay timers that only exist in the full GCM.

Fixes for fv3 standalone

---

.circleci/config.yml
StandAlone_AdvCore.F90
StandAlone_DynAdvCore.F90
StandAlone_FV3_Dycore.F90

Supersedes #239 
This is a handmerge of `develop` into `release/MAPL-v3` where I'm using the CI to make sure all the edits are right. Or at least the one we test.

Handmerge develop into MAPL3 - 2023-Jun-09

---

scripts/fv3_setup

Updates `fv3_setup` to get the MPI stack from CMake rather than using `BASEDIR`. Requires ESMA_cmake v3.41.0 (see https://github.com/GEOS-ESM/GEOSfvdycore/pull/110)

Use CMake to determine MPI Stack

---

FV_StateMod.F90

NOTE: View changes with whitespace off:
https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/280/files?w=1
as my editor cleans up trailing spaces.
---
This PR fixes a small bug in `FV_StateMod` found by @atrayano where this:
```fortran
if (FV_Atm(1)%flagstruct%npz == 1) SW_DYNAMICS = .true.
```
was being called before:
```fortran
call MAPL_GetResource( MAPL, FV_Atm(1)%flagstruct%npz, 'AGCM_LM:', default= 72, RC=STATUS )
```
This is an obvious bug as you shouldn't refer to a variable before it's set.
I will test this along with  https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/96  with both Intel and GCC to make sure it is zero diff.

Fix use of npz before being set

---

CMakeLists.txt

This PR adds a dependency to `fms_r4`. We need this because of the weird way we build FV3 as r4 but link to the r8 version of FMS. In that case, we still need to point to the include files from r4 FMS. 
But, CMake in that case has no idea that to build, say, Moist, that we need to build `fms_r4` before building this.
This change is *NOT* needed in GEOSgcm v12 because in that case FMS is in Baselibs/Spack and so CMake doesn't need to know. I've added a big fat comment for the inevitable case when a merge to v12 happens and the build fails.

v11: Add dependency to fms_r4

---

.circleci/config.yml
CMakeLists.txt

Testing with spack showed there were still non-standard fms targets in the CMake code. This converts them all to the "correct" `FMS::` style targets.

v12: Update CMake to use FMS:: targets

---

fv_regrid_c2c.F90
interp_restarts.F90

This is a companion to https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/107 to allow R8 builds of FV again. 
This is zero-diff for the regular 32-bit GEOSgcm runs.

v12: precision fixes for R8 Builds

---

scripts/fv3_setup

This PR removes NCCS OS detection

v11: Remove NCCS OS detection
